name: videomae
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch::pytorch=2.0.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pillow
  - pip:
    - av==15.0.0
    - git+https://github.com/dmlc/decord.git
    - deepspeed
    - einops
    - opencv-python
    - safetensors
    - tensorboard==2.9.0
    - tensorboardX==1.8
    - timm==0.4.12
    - triton==1.0.0
